name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: describe
    attributes:
      label: Describe the bug
      description: Please tell us what went wrong
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Please tell us what you did to get this error
      description: If you can provide a simple example, please also put it below!
      value: "1. Go to '...'\n2. Click on '....'\n3. Scroll down to '....'\n4. See error"
